import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { ApolloWrapper } from "@/components/ApolloWrapper";

export const metadata: Metadata = {
  title: "Nest TODO App",
  description: "Generated by create next & next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Theme>
          <ApolloWrapper>{children}</ApolloWrapper>
        </Theme>
      </body>
    </html>
  );
}
