import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { getCurrentFirebaseUser } from "@/lib/auth/server/auth";
import { getSession, signOutSession } from "@/lib/auth/server/session";
import { redirect } from "next/navigation";
import Header from "./_components/Header";
import { getCurrentViewer } from "@/lib/auth/server/get-current-viewer";

export const metadata: Metadata = {
  title: "Nest TODO App",
  description: "Generated by create next & next app",
};

export default async function OnboardingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { currentUser } = await getCurrentFirebaseUser(await getSession());
  if (currentUser == null) {
    redirect("/login");
  }

  const viewer = await getCurrentViewer();
  if (viewer != null) {
    // NOTE: onboardingが終わるとユーザープロファイルがサーバー上で作成される
    redirect("/tasks");
  }

  async function signOut() {
    "use server";
    await signOutSession();
  }

  return (
    <>
      <Header user={currentUser} onSignOut={signOut} />
      {children}
    </>
  );
}
